# Instructions:
# `docker build --build-arg SSH_PUBKEY=/path/to/id_rsa.pub -t conordonihoo/vmbase:<tag> .`
# `docker run -t -d -p 2222:22 -v /path/on/host:/path/in/container --name vmbase conordonihoo/vmbase:<tag>`
# `docker exec -it vmbase bash`

# Base OS image
FROM ubuntu:24.04

# -----------------------
# Ubuntu
# -----------------------

# Avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Standard update and install essential packages
RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    python-is-python3 \
    gcc \
    vim \
    neovim \
    ripgrep \
    fd-find \
    direnv \
    tmux \
    git \
    curl \
    openssh-server \
    sudo \
    locales && \
    rm -rf /var/lib/apt/lists/*

# Set locale
RUN locale-gen en_US.UTF-8
ENV LC_CTYPE="en_US.UTF-8"
ENV LANG="en_US.UTF-8"
ENV TERM="xterm-256color"

# -----------------------
# User
# -----------------------

# Create user "conor" with sudo privileges
RUN useradd -m -s /bin/bash conor && \
    echo "conor ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/conor && \
    chmod 0440 /etc/sudoers.d/conor

# Working directory
WORKDIR /home/conor

# -----------------------
# Synced
# -----------------------

RUN mkdir /home/conor/synced && \
    chown -R conor:conor /home/conor/synced

# -----------------------
# Python
# -----------------------

# Create the virtual environment
RUN python3 -m venv /home/conor/.venv && \
    chown -R conor:conor /home/conor/.venv && \
    echo 'source /home/conor/.venv/bin/activate' > /etc/profile.d/venv.sh && \
    chmod +x /etc/profile.d/venv.sh

# -----------------------
# SSH
# -----------------------

# Configure SSH
RUN mkdir /var/run/sshd && \
    mkdir /home/conor/.ssh && \
    chown -R conor:conor /home/conor/.ssh

# Copy public key into authorized keys
ARG SSH_PUBKEY
COPY ${SSH_PUBKEY} /home/conor/.ssh/authorized_keys

# Start SSH service when container runs
CMD ["/usr/sbin/sshd", "-D"]
